version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
    groups:
      all-pip-deps:
        patterns:
          - "*"
    post-update-commands:
      - "pipx install uv"
      - "uv lock"
